version: "3.3"

services:
  db:
    image: postgres
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    labels:
      name: "Postgres SQL Database"
