#!/bin/bash

unset APP_DEVELOPMENT_DB
unset APP_DEVELOPMENT_USER
unset APP_DEVELOPMENT_PASS

unset APP_TESTING_DB
unset APP_TESTING_USER
unset APP_TESTING_PASS

unset APP_PRODUCTION_DB
unset APP_PRODUCTION_USER
unset APP_PRODUCTION_PASS

